<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL0gtJcs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL0gtJcs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL0gtJcs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL0gtJcs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL0gtJcs\App_KernelDevDebugContainer([
    'container.build_hash' => 'L0gtJcs',
    'container.build_id' => 'ea7714dd',
    'container.build_time' => 1688132332,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL0gtJcs');
